### ISSUE TITLE
Feature Creation Attempt

### ISSUE THREAD

**Issue by anordin95** [HDI-Project/ballet-predict-house-prices#35]
I'm attempting to validate my new feature using:
```
from ballet import b
b.validate_feature_api(feature)
# True
```

![image](https://user-images.githubusercontent.com/7705027/93836602-46e22e00-fc51-11ea-8be0-6b0deb3b7235.png)

For reference, here's the file I'm executing: 
```
from ballet import Feature, b

input = ['MS SubClass']  # TODO - str or list of str
transformer = None  # TODO - function, transformer-like, or list thereof
name = 'Dwelling type identifier'  # TODO - str
feature = Feature(input, transformer, name)

# b.validate_feature_api(feature)
b.validate_feature_acceptance(feature)
```

I suspect some aspect of configuration went awry. I was unable to successfully perform the `invoke install` step.

![image](https://user-images.githubusercontent.com/7705027/93836693-97f22200-fc51-11ea-84c8-353ddd6828fe.png)

**Comment by micahjsmith** [comment]
Hi @anordin95, thanks for reporting!

Looks like the steps you are following from the Contributor Guide are from a newer version of ballet, so they didn't quite work in this project which runs an older version.

I've updated this project to use the newest version of ballet and if you retry what you are doing it should now work

Closed by 7e369aa
